remote_theme: just-the-docs/just-the-docs@v0.10.0

title: kubectl-safed
description: Safer Kubernetes node drains through workload-aware rolling restarts

color_scheme: dark

search_enabled: true
nav_enabled: true

plugins:
  - jekyll-remote-theme
